apiVersion: apps/v1
kind: Deployment
metadata:
  name: aluminium-server
  labels:
    app: aluminium-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aluminium-server
  template:
    metadata:
      labels:
        app: aluminium-server
    spec:
      containers:
        - name: aluminium-server
          # The GitHub Actions workflows will automatically replace this tag string with the commit SHA
          image: ghcr.io/pandatwoxx/aluminium/aluminium-server:20a5436ca06702dd5f0c725c68df1372c9ac95b2
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URI
              value: "mongodb://mongodb-local:27017/aluminium_packages"
---
apiVersion: v1
kind: Service
metadata:
  name: aluminium-server
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: aluminium-server